import { IuserDetail, typeMenuItem, typeUserItem } from './user.type';

export const users: typeUserItem[] = [
  { id: 1, name: 'kongkong', password: '123456' },
  { id: 2, name: 'coderwhy', password: '123456' },
];

export const menus: typeMenuItem[] = [
  {
    id: 1,
    name: '系统总览',
    type: 1,
    url: '/main/analysis',
    icon: 'el-icon-monitor',
    children: [
      {
        id: 39,
        url: '/main/analysis/overview',
        name: '核心技术',
        type: 2,
        children: null,
        parentId: 1,
      },
      {
        id: 40,
        url: '/main/analysis/dashboard',
        name: '商品统计',
        type: 2,
        children: null,
        parentId: 1,
      },
    ],
  },
  {
    id: 2,
    name: '系统管理',
    type: 1,
    url: '/main/system',
    icon: 'el-icon-setting',
    children: [
      {
        id: 41,
        url: '/main/system/user',
        name: '用户管理',
        type: 2,
        children: [
          {
            id: 50,
            url: null,
            name: '创建用户',
            type: 3,
            parentId: 41,
            permission: 'system:user:create',
          },
          {
            id: 51,
            url: null,
            name: '删除用户',
            type: 3,
            parentId: 41,
            permission: 'system:user:delete',
          },
          {
            id: 52,
            url: null,
            name: '修改用户',
            type: 3,
            parentId: 41,
            permission: 'system:user:edit',
          },
          {
            id: 53,
            url: null,
            name: '查询用户',
            type: 3,
            parentId: 41,
            permission: 'system:user:find',
          },
        ],
        parentId: 2,
      },
      {
        id: 42,
        url: '/main/system/department',
        name: '部门管理',
        type: 2,
        children: [
          {
            id: 54,
            url: null,
            name: '创建角色',
            type: 3,
            parentId: 42,
            permission: 'system:department:create',
          },
          {
            id: 55,
            url: null,
            name: '删除部门',
            type: 3,
            parentId: 42,
            permission: 'system:department:delete',
          },
          {
            id: 56,
            url: null,
            name: '修改部门',
            type: 3,
            parentId: 42,
            permission: 'system:department:edit',
          },
          {
            id: 57,
            url: null,
            name: '查询部门',
            type: 3,
            parentId: 42,
            permission: 'system:department:find',
          },
        ],
        parentId: 2,
      },
      {
        id: 43,
        url: '/main/system/menu',
        name: '菜单管理',
        type: 2,
        children: null,
        parentId: 2,
      },
      {
        id: 44,
        url: '/main/system/role',
        name: '角色管理',
        type: 2,
        children: [
          {
            id: 58,
            url: null,
            name: '创建角色',
            type: 3,
            parentId: 44,
            permission: 'system:role:create',
          },
          {
            id: 59,
            url: null,
            name: '删除角色',
            type: 3,
            parentId: 44,
            permission: 'system:role:delete',
          },
          {
            id: 60,
            url: null,
            name: '修改角色',
            type: 3,
            parentId: 44,
            permission: 'system:role:edit',
          },
          {
            id: 61,
            url: null,
            name: '查询角色',
            type: 3,
            parentId: 44,
            permission: 'system:role:find',
          },
        ],
        parentId: 2,
      },
    ],
  },
  {
    id: 3,
    name: '商品中心',
    type: 1,
    url: '/main/product',
    icon: 'el-icon-goods',
    children: [
      {
        id: 45,
        url: '/main/product/category',
        name: '商品类别',
        type: 2,
        children: null,
        parentId: 3,
      },
      {
        id: 46,
        url: '/main/product/goods',
        name: '商品信息',
        type: 2,
        children: null,
        parentId: 3,
      },
    ],
  },
  {
    id: 4,
    name: '随便聊聊',
    type: 1,
    url: '/main/story',
    icon: 'el-icon-chat-line-round',
    children: [
      {
        id: 47,
        url: '/main/story/chat',
        name: '你的故事',
        type: 2,
        children: null,
        parentId: 4,
      },
      {
        id: 48,
        url: '/main/story/list',
        name: '故事列表',
        type: 2,
        children: null,
        parentId: 4,
      },
    ],
  },
];

export const detailInfo: IuserDetail[] = [
  {
    id: 1,
    name: 'kongkong',
    realname: 'lin',
    cellphone: '15900004142',
    enable: 1,
    createAt: '2024-4-14',
    updateAt: '2024-4-14',
    department: {
      id: 1,
      name: '董事会',
      parentId: null,
      leader: 'ray',
    },
    role: {
      id: 1,
      name: '超级管理员',
      intro: '所有权限',
      menus: [1, 2, 3, 4, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
    },
  },
  {
    id: 2,
    name: 'coderwhy',
    realname: 'teacher',
    cellphone: '15600004321',
    enable: 1,
    createAt: '2022-4-14',
    updateAt: '2024-4-14',
    department: {
      id: 4,
      name: '技术部',
      parentId: 1,
      leader: 'Tao',
    },
    role: { id: 2, name: '普通管理员', intro: '部分权限', menus: [1, 2] },
  },
  {
    id: 3,
    name: 'ray',
    realname: '张三',
    cellphone: '19987021563',
    enable: 1,
    createAt: '2023-4-14',
    updateAt: '2024-4-14',
    department: {
      id: 3,
      name: '人力资源部',
      parentId: 1,
      leader: 'Allen',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 4,
    name: 'allen',
    realname: '李四',
    cellphone: '18844439612',
    enable: 1,
    createAt: '2021-4-14',
    updateAt: '2024-4-14',
    department: {
      id: 5,
      name: '法务部',
      parentId: 1,
      leader: 'Taylor',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 5,
    name: 'bush',
    realname: '王五',
    cellphone: '12345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 6,
    name: 'shift',
    realname: '王劳达',
    cellphone: '12345224967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 7,
    name: 'buddism',
    realname: '悉达多',
    cellphone: '12345334819',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 8,
    name: '不吃香菜',
    realname: '阿紫',
    cellphone: '66645334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 9,
    name: 'Amen',
    realname: '阿门',
    cellphone: '12345334221',
    enable: 1,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 10,
    name: 'daoism',
    realname: '老子',
    cellphone: '12345334991',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 11,
    name: 'God',
    realname: '耶稣',
    cellphone: '12300004967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 12,
    name: 'damn',
    realname: '川普',
    cellphone: '12345300967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 13,
    name: 'lady',
    realname: '小婕',
    cellphone: '52045334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 14,
    name: 'crush',
    realname: '许某',
    cellphone: '12345312367',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
  {
    id: 15,
    name: 'rush',
    realname: '牛爷爷',
    cellphone: '111345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: {
      id: 2,
      name: '行政部',
      parentId: 1,
      leader: 'lin',
    },
    role: {
      id: 3,
      name: '员工',
      intro: '仅供系统总览和随便聊聊',
      menus: [1, 3],
    },
  },
];
