import { IuserDetail } from './user.type';

export const users = [
  { id: 1, name: 'kongkong', password: '123456' },
  { id: 2, name: 'coderwhy', password: '123456' },
];

export const menus = [
  {
    id: 1,
    name: '系统总览',
    type: 1,
    url: '/main/analysis',
    icon: 'el-icon-monitor',
    children: [
      {
        id: 39,
        url: '/main/analysis/overview',
        name: '核心技术',
        type: 2,
        children: null,
        parentId: 1,
      },
      {
        id: 40,
        url: '/main/analysis/dashboard',
        name: '商品统计',
        type: 2,
        children: null,
        parentId: 1,
      },
    ],
  },
  {
    id: 2,
    name: '系统管理',
    type: 1,
    url: '/main/system',
    icon: 'el-icon-setting',
    children: [
      {
        id: 41,
        url: '/main/system/user',
        name: '用户管理',
        type: 2,
        children: null,
        parentId: 2,
      },
      {
        id: 42,
        url: '/main/system/department',
        name: '部门管理',
        type: 2,
        children: null,
        parentId: 2,
      },
      {
        id: 43,
        url: '/main/system/menu',
        name: '菜单管理',
        type: 2,
        children: null,
        parentId: 2,
      },
      {
        id: 44,
        url: '/main/system/role',
        name: '角色管理',
        type: 2,
        children: null,
        parentId: 2,
      },
    ],
  },
  {
    id: 3,
    name: '商品中心',
    type: 1,
    url: '/main/product',
    icon: 'el-icon-goods',
    children: [
      {
        id: 45,
        url: '/main/product/category',
        name: '商品类别',
        type: 2,
        children: null,
        parentId: 3,
      },
      {
        id: 46,
        url: '/main/product/goods',
        name: '商品信息',
        type: 2,
        children: null,
        parentId: 3,
      },
    ],
  },
  {
    id: 4,
    name: '随便聊聊',
    type: 1,
    url: '/main/story',
    icon: 'el-icon-chat-line-round',
    children: [
      {
        id: 47,
        url: '/main/story/chat',
        name: '你的故事',
        type: 2,
        children: null,
        parentId: 4,
      },
      {
        id: 48,
        url: '/main/story/list',
        name: '故事列表',
        type: 2,
        children: null,
        parentId: 4,
      },
    ],
  },
];
export const detailInfo: IuserDetail[] = [
  {
    id: 1,
    name: 'kongkong',
    realname: 'lin',
    cellphone: '15900004142',
    enable: 1,
    createAt: '2024-4-14',
    updateAt: '2024-4-14',
    department: { id: 1, name: '总裁办' },
    role: { id: 1, name: '超级管理员', intro: '所有权限' },
  },
  {
    id: 2,
    name: 'coderwhy',
    realname: 'teacher',
    cellphone: '15600004321',
    enable: 1,
    createAt: '2022-4-14',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 3,
    name: 'ray',
    realname: '张三',
    cellphone: '19987021563',
    enable: 1,
    createAt: '2023-4-14',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 4,
    name: 'allen',
    realname: '李四',
    cellphone: '18844439612',
    enable: 1,
    createAt: '2021-4-14',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 5,
    name: 'bush',
    realname: '王五',
    cellphone: '12345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 6,
    name: 'bush',
    realname: '王五',
    cellphone: '12345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 7,
    name: 'bush',
    realname: '王五',
    cellphone: '12345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 8,
    name: 'bush',
    realname: '王五',
    cellphone: '12345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 9,
    name: 'bush',
    realname: '王五',
    cellphone: '12345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 10,
    name: 'shift',
    realname: '王劳达',
    cellphone: '12345224967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 11,
    name: 'buddism',
    realname: '悉达多',
    cellphone: '12345334819',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 12,
    name: '不吃香菜',
    realname: '阿紫',
    cellphone: '66645334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 13,
    name: 'daoism',
    realname: '老子',
    cellphone: '12345334991',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 14,
    name: 'God',
    realname: '耶稣',
    cellphone: '12300004967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 15,
    name: 'damn',
    realname: '川普',
    cellphone: '12345300967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 16,
    name: 'lady',
    realname: '小婕',
    cellphone: '52045334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 17,
    name: 'crush',
    realname: '许某',
    cellphone: '12345312367',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
  {
    id: 18,
    name: 'rush',
    realname: '牛爷爷',
    cellphone: '111345334967',
    enable: 0,
    createAt: '2022-1-11',
    updateAt: '2024-4-14',
    department: { id: 2, name: '技术部' },
    role: { id: 3, name: '员工', intro: '仅供系统总览和随便聊聊' },
  },
];
